# -*- coding: utf-8 -*-
"""security.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGSq-c_T1QMTNZUNee4DTATw3_qxwjHj
"""

import opendatasets as od
od.download('https://www.kaggle.com/datasets/dhoogla/unswnb15?resource=download&select=UNSW_NB15_training-set.parquet')

import pandas as pd
df = pd.read_parquet('/content/unswnb15/UNSW_NB15_training-set.parquet')

import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras import layers, models
from tensorflow.keras.layers import Embedding,Input,Flatten,Dense
from tensorflow.keras.models import Model

from sklearn.preprocessing import StandardScaler, LabelEncoder
scaler = StandardScaler()

import numpy as np

cat_cols = ['service', 'state']

df = pd.get_dummies(df, columns=cat_cols, dtype=int)

num_cols = df.select_dtypes(include=['int64', 'float64','float32','int8','int16','int32']).columns
num_cols = num_cols.drop('proto', errors='ignore')
num_cols = num_cols.drop('label', errors='ignore')
df[num_cols] = scaler.fit_transform(df[num_cols])

le = LabelEncoder()
X_proto = le.fit_transform(df['proto'])
X_num = df[num_cols].values
y_data = df['label'].values

proto_in = Input(shape=(1,),name = 'proto_in')
proto_emb = Embedding(input_dim=133, output_dim=8,)(proto_in)

proto_vec = Flatten()(proto_emb)

num_in = Input(shape=(X_num.shape[1],), name='other_input')


x = layers.Concatenate()([proto_vec,num_in])

from sklearn.model_selection import train_test_split

X_proto_train, X_proto_val, X_num_train, X_num_val, y_train, y_val = train_test_split(
    X_proto, X_num, y_data,
    test_size=0.2,
    random_state=42,
    stratify=y_data
)

X_proto_train.shape

x = layers.Dense(64, activation='relu')(x)
x = layers.Dropout(0.2)(x)
x = layers.Dense(32, activation='relu')(x)
x = layers.Dropout(0.3)(x)
x = layers.Dense(64, activation='relu')(x)
x = layers.Dropout(0.2)(x)
x = layers.Dense(32, activation='relu')(x)
x = layers.Dropout(0.3)(x)
x = layers.Dense(16, activation='relu')(x)

output = layers.Dense(1, activation='sigmoid')(x)
model = models.Model(inputs=[proto_in, num_in], outputs=output)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy',tf.keras.metrics.AUC(name='auc'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall')] )
model.summary()

X_num_train.shape, X_proto_train.shape

history = model.fit(
    {'proto_in': X_proto_train, 'other_input': X_num_train},
    y=y_train,
    epochs=20,
    batch_size=64,
    verbose=1,
    validation_data=(
        {'proto_in': X_proto_val, 'other_input': X_num_val},
        y_val
    )
)